[versions]
android-minSdk = "28"
android-compileSdk = "36"
androidx-annotationJvm = "1.10.0"
agp = "9.0.1"
dokka = "2.2.0"
icu = "78.3"
kotest = "6.2.4"
kotlin = "2.4.10"
kotlinpoet = "2.3.0"
kotlinx-coroutines = "1.11.0"
kotlinx-datetime = "0.8.0"
ktlint-plugin = "14.2.0"
ksp = "2.3.6"
mokkery = "3.4.2"
semver = "3.1.0"
vanniktechMavenPublish = "0.37.0"

[libraries]
androidx-annotationJvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "androidx-annotationJvm" }
dokka-versioning = { module = "org.jetbrains.dokka:versioning-plugin", version.ref = "dokka" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-runner-junit4 = { module = "io.kotest:kotest-runner-junit4", version.ref = "kotest" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ibm-icu4j = { module = "com.ibm.icu:icu4j", version.ref = "icu" }
semver = { module = "io.github.z4kn4fein:semver", version.ref = "semver" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
js-plain-objects = { id = "org.jetbrains.kotlin.plugin.js-plain-objects", version.ref = "kotlin" }
kotest = { id = "io.kotest", version.ref = "kotest" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
