name: Store Dokka documentation

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate Dokka docs
        run: ./gradlew dokkaGenerateHtml

      # IMPORTANT: Checkout of Dokka branch is done AFTER generating docs
      - name: Checkout dokka branch
        uses: actions/checkout@v4
        with:
          ref: dokka
          path: dokka

      - name: Store generated docs in dokka branch
        run: ./gradlew storeDokkaHtml

      - name: Store generated docs in dokka branch
        id: version
        run: echo "version=$(./gradlew getCurrentVersion --quiet)" >> "$GITHUB_OUTPUT"

      - name: Commit dokka branch
        uses: EndBug/add-and-commit@v10
        with:
          cwd: dokka
          message: Add/update Dokka documentation for v${{ steps.version.outputs.version }}
