name: Publish RELEASE to Maven Central
run-name: Publish RELEASE ${{ github.event.release.tag_name }} to Maven Central
on:
  release:
    types: [released, prereleased]
jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - id: version
        run: |
          TAG=${{ github.event.release.tag_name }}
          VERSION="${TAG#v}"

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  publish:
    needs: prepare
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      version: ${{ needs.prepare.outputs.version }}
      release: false
